--- 
version: "3.2"
services: 
  codeserver:
    command: "--allow-http"
    container_name: codeserver
    env_file:
      - cs.env
    image: "codercom/code-server:latest"
    ports: 
      - "8443:8443"
    restart: always
    volumes: 
      - "jingkai_cs_data:/root/project"
      - jingkai_cs_settings:/home/coder/.local/share/code-server
volumes: 
  jingkai_cs_data: 
    driver: local-persist
    driver_opts: 
      mountpoint: /home/jingkai/code-server/cs_data
  jingkai_cs_settings:
    driver: local-persist
    driver_opts:
      mountpoint: /home/jingkai/code-server/cs_settings
